import {Analysis,TradeIdea} from '@/types';
function clamp(n:number,a:number,b:number){return Math.max(a,Math.min(b,n))}
export function analyzeTrade(idea:TradeIdea):Analysis{
 const {asset,side,confidence,thesis}=idea; const momentum=Math.abs(asset.change24h); const evidence=clamp(Math.round(78 - asset.volatility*.25 + momentum*2 + (thesis.length>35?8:0)),28,91); const gap=Math.max(0,confidence-evidence); const late=momentum>3.5; const volatile=asset.volatility>60; const weak=thesis.trim().length<25;
 const blockers:number[]=[]; if(gap>=25) blockers.push(1); if(volatile) blockers.push(1); if(weak) blockers.push(1); if(side==='BUY'&&asset.change24h>4) blockers.push(1); if(side==='SELL'&&asset.change24h<-4) blockers.push(1);
 const verdict=blockers.length>=2?'REJECT':blockers.length===1?'WAIT':'EXECUTE';
 const headline=verdict==='EXECUTE'?'Your trade survived the challenge.':'Your confidence needs more evidence before this trade earns approval.';
 const entryLow=asset.price*(side==='SELL'?1.002:.992),entryHigh=asset.price*(side==='SELL'?1.012:1.008),invalidation=side==='SELL'?asset.price*1.025:asset.price*.975;
 return {id:crypto.randomUUID(),asset,side,confidence,evidenceQuality:evidence,confidenceGap:gap,verdict,headline,
 bullCase:[`${asset.name} has ${asset.change24h>=0?'positive':'recovering'} short-term momentum.`,`Current volatility (${asset.volatility}%) still leaves room for disciplined sizing.`,`The setup can work if price confirms rather than immediately reversing.`],
 mirrorCase:[...(late?[`Entry may be chasing an extended ${momentum.toFixed(1)}% move.`]:[]),...(volatile?[`Volatility is elevated; a normal move can invalidate a tight stop.`]:[]),...(weak?[`Your thesis is too thin to justify the confidence level.`]:[]),...(gap>=20?[`Your ${confidence}% confidence is ${gap} points above the evidence score.`]:[`The evidence is reasonably aligned with your confidence.`])],
 risks:[`Market volatility: ${asset.volatility}%`,`${side==='BUY'?'Downside':'Upside'} invalidation near ${invalidation.toFixed(2)}`,gap>=20?'Confidence/evidence mismatch':'No major confidence mismatch detected'],
 whatChangesMind:[`Wait for price to confirm the entry zone ${entryLow.toFixed(2)}–${entryHigh.toFixed(2)}.`,`Keep maximum loss at or below ${idea.amount?Math.min(1,Math.round(100*1000/Math.max(idea.amount,1))/100):1}%.`,`If the thesis changes, rerun the challenge instead of averaging down.`],
 entryLow,entryHigh,invalidation,maxRiskPct:1,rr:2.4,agents:[{name:'Trader',role:'Build the case',status:confidence>=60?'PASS':'WARN',summary:`${side} ${asset.name} based on momentum and thesis.`},{name:'Mirror',role:'Attack the thesis',status:gap>=20||volatile||weak?'WARN':'PASS',summary:gap>=20?'Confidence exceeds evidence.':'No decisive contradiction found.'},{name:'Risk Guardian',role:'Enforce hard limits',status:volatile?'WARN':'PASS',summary:volatile?'Volatility requires smaller sizing.':'Exposure constraints are acceptable.'},{name:'Judge',role:'Issue verdict',status:verdict==='REJECT'?'BLOCK':verdict==='WAIT'?'WARN':'PASS',summary:headline}],marketSnapshot:{price:asset.price,change24h:asset.change24h,volatility:asset.volatility,volumeScore:Math.round(50+Math.random()*45)},createdAt:new Date().toISOString()};
}
